version: "3"
services:
  redis:
    image: redis
    container_name: redis_cache
    expose:
      - 6379
  app:
    build: ./
    command: ./app
    links:
      - redis:redis
    environment:
      - REDIS_URI=redis:6379
      - PORT=8080
    ports:
      - 8080:8080